version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Füge hier deine Firebase-Configs hinzu, falls du sie nicht im Code hartkodiert hast
    restart: always
